// <auto-generated />
using System;
using Jay.NC.Workflow.WebApi.Storage.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jay.NC.Workflow.WebApi.Storage.Migrations
{
    [DbContext(typeof(WorkflowDbContext))]
    [Migration("20251013020902_addTab_SystemConfig")]
    partial class addTab_SystemConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Jay.NC.Workflow.WebApi.Storage.Entity.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_time");

                    b.Property<int>("Creator")
                        .HasColumnType("int")
                        .HasColumnName("creator");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_time");

                    b.Property<int?>("Deleter")
                        .HasColumnType("int")
                        .HasColumnName("deleter");

                    b.Property<string>("DeptIcon")
                        .HasColumnType("longtext")
                        .HasColumnName("dept_icon");

                    b.Property<Guid>("DeptId")
                        .HasColumnType("char(36)")
                        .HasColumnName("dept_id");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("dept_name");

                    b.Property<int?>("DeptTypeId")
                        .HasColumnType("int")
                        .HasColumnName("dept_type_id");

                    b.Property<string>("DeptTypeName")
                        .HasColumnType("longtext")
                        .HasColumnName("dept_type_name");

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_time");

                    b.Property<int?>("Modifier")
                        .HasColumnType("int")
                        .HasColumnName("modifier");

                    b.Property<Guid?>("ParentDeptId")
                        .HasColumnType("char(36)")
                        .HasColumnName("parent_dept_id");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext")
                        .HasColumnName("remark");

                    b.Property<int>("SortNo")
                        .HasColumnType("int")
                        .HasColumnName("sort_no");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("department");
                });

            modelBuilder.Entity("Jay.NC.Workflow.WebApi.Storage.Entity.SystemConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfigKey")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("config_key");

                    b.Property<string>("ConfigName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("config_name");

                    b.Property<int>("ConfigType")
                        .HasColumnType("int")
                        .HasColumnName("config_type");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("config_value");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_time");

                    b.Property<int>("Creator")
                        .HasColumnType("int")
                        .HasColumnName("creator");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_time");

                    b.Property<int?>("Deleter")
                        .HasColumnType("int")
                        .HasColumnName("deleter");

                    b.Property<string>("ExtData")
                        .HasColumnType("longtext")
                        .HasColumnName("ext_data");

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_time");

                    b.Property<int?>("Modifier")
                        .HasColumnType("int")
                        .HasColumnName("modifier");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext")
                        .HasColumnName("remark");

                    b.Property<int>("SortNo")
                        .HasColumnType("int")
                        .HasColumnName("sort_no");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("system_config");
                });
#pragma warning restore 612, 618
        }
    }
}
